# Python packages


We do specialized tasks in Python with _packages_. A package is a collection of Python functions that someone wrote and bundled together for you to use. Some of the Python packages that we'll learn to use include this summer are listed below. You might remember that we installed these packages when we get you set up with Anaconda! 

| Package | Uses                     |
|---------|--------------------------|
| `numpy` | Math with arrays (more on this below) | 
| `scipy` | A math toolkit built for use by scientists | 
| `matplotlib` | Visualization (plotting!) | 
| `astropy` | Astronomy-specific functions of all kinds | 

## Numpy

Numpy is the most important package that we're going to teach you about, because it allows you to do calculations very quickly with Python. Below, we'll discover why it's useful.

*** 

Let's say you want to take the $\sin$ or $\cos$ of an angle. There are numpy function that do this for you. 

To gain access to numpy's functions, you always need to do this command first: 
```python
import numpy as np
```
Copy-paste the code in the line above and run it in the cell below: 

In [1]:
import numpy as np

Now there's a _package_ stored in the variable called `np` that we can access in any cell in this notebook. There are _functions_ for `sin` and `cos` that live within numpy. The way to access a function within a package is by calling the function name with a period after it, then the name of the function you want. So for `sin`, you can do: 
```python
np.sin(0)
```
The `np.` part says "give me this function from numpy". The `sin()` part says "the function that I want to use is `sin`, and the `0` is the argument we are feeding into the function, which is the angle that we want to take the `sin` of, in units of radians (not degrees). Run that line in the cell below, and experiment with different angles. Try `np.cos` too.

In [2]:
np.sin(0)

0.0

In [3]:
np.cos(0)

1.0

Numpy also has some built-in numbers that you might use. For example, $\pi$ is stored (to high precision!), in `np.pi`. Print out numpy's $\pi$ in the cell below: 

In [4]:
np.pi

3.141592653589793

Now let's say you had a list of angles, like `angles`$= [0, \pi/2, \pi, 3\pi/2, 2\pi]$. You could call `np.sin(angles[0])` to get the $\sin$ of the first angle, then `np.sin(angles[1])` on the second angle, etc. But that would be a really slow way to do it! 

### Arrays

The quick way is to create a _numpy array_. A `numpy` array very similar to a python list, but is native to the ```numpy``` package. Mathematically, a `numpy` array is a vector or matrix of numbers, which can be used for more advanced math. ```numpy``` can act on arrays more efficiently than Python can with ordinary lists.

Let's make a numpy array filled with the angles above:
```python
# First, here's the list that we want to have an array of: 
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

# Here's how we make a numpy array out of the list
angle_array = np.array(angle_list)
```
Write out those lines in the cell below. 

In [5]:
# First, here's the list that we want to have an array of: 
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

# Here's how we make a numpy array out of the list
angle_array = np.array(angle_list)

Let's break down the command `np.array(angle_list)`. The `np.` says we're going to use a function from numpy, the `array()` says we're going to make an array out of the thing in the parentheses, and the `angle_list` is the _input_ or the _argument_ of the function. 

Now you can do things with the numpy array that you couldn't do with a Python list. Here are some of them, which you should experiment with in the cell below: 
```python
# Sum of all elements in the array:
angle_array.sum()

# Mean of all elements in the array:
angle_array.mean()

# Maximum of the elements in the array:
angle_array.max()

# Minimum of the elements in the array: 
angle_array.min()

# Standard deviation of the elements in the array: 
angle_array.std()
```

If you want to keep the formatting more similar to the other function's we've been running, you can also run them this way:
```python
# Sum of all elements in the array:
np.sum(angle_array)

# Mean of all elements in the array:
np.mean(angle_array)

# Maximum of the elements in the array:
np.max(angle_array)

# Minimum of the elements in the array: 
np.min(angle_array)

# Standard deviation of the elements in the array: 
np.std(angle_array)
```

Try running each of the above commands one-by-one in the cell below to see what they output.

In [6]:
np.std(angle_array)

2.221441469079183

### Syntax Tips and Help ###
So what happens when you forget the name of a `numpy` function, or the how to use a particular function? `Jupyter` has some cool built-in features that you should take advantage of!

For example, say you forgot the name of the `sum` function -- you can type `np.` and then press `tab`, and you'll see that the notebook lists what functions are available in `numpy`! Spoiler alert, it's a loooong list since `numpy` has many functionalities. 

The point is you can use the `tab` tool (recall tab completion trick) to help you remember or recognize the function you're looking for. 

Just like how in `bash` environments you can read details on how to use a function, you can do that in `Python` as well. For example, say you forgot how to use the `np.sin` function -- you can type `np.sin?` + `Cntrl`+`return` and the notebook will return an inline window that tells you almost everything you need to know about the function. 

Try playing around with `np.` + `tab` and `np.cos?`, or any function with a `?` at the end, below.

In [7]:
np.sin?

### Example 1: Calculations with arrays

What is the $\sin$ and $\cos$ of each angle? Use the numpy array `angle_array` as the argument to the `np.sin` and `np.cos` functions in the cell below:

In [8]:
np.sin(angle_array)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

Now you might be saying - wait a minute, $\sin(3\pi/2) = 0$, not $\approx$`1e-16`, what's that about? The short answer is - computers often get very very close to approximating the numbers that we actually want, but not all of the way there. You can get better precision if you tell the computer to use more memory, which we can talk about after class if you like. 

***

## Array arithmetic

There are lots of situations where you'll want to create a certain kind of array, and numpy has functions to help. 

You can make an array of consecutive integers from zero to nine with the function `np.arange`:
```python
consecutive_integers = np.arange(10)
```
This function returns different things depending on the amount of _arguments_ that you give it. If there's one number in the parentheses, it tells `np.arange` what number to stop at (exclusive). If there are three numbers, they signify `np.arange(start, stop, step)`. For example, `np.arange(1, 9, 2)` would start at 1, stop before 9, with a step size of 2, so it would return `[1, 3, 5, 7]`.

In the cell below, make an array with 10,000 sequential integers, starting with the zero. Save the array into a variable called `consecutive_integers`, and print it out:

In [9]:
consecutive_integers = np.arange(10000)

You'll see that numpy is polite. It knows you probably don't want to see all ten thousand integers, so it prints just the beginning and end of the array. 

### Exercise 2: Indexing/slicing numpy arrays
The same indexing and slicing rules that we learned for lists work on arrays. Keep in mind that arrays are indexed starting with 0, just like ```Python``` lists and when you give a range of indexes, it won't include the last one listed. In the cell below, print the 42nd element of the `consecutive_integers` array, and print the 101-103rd (inclusive) elements of the array:

In [13]:
consecutive_integers[41]

41

In [15]:
consecutive_integers[100:103]

array([100, 101, 102])

Unlike lists, you can do arithmetic with numpy arrays. For example, if you had the following list: 
```python
heights = [162, 185, 174, 191]
```
and you tried to add one to the list, this is what you would get: 
```python
print(heights + 1)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-23-ca23c21090bd> in <module>()
      1 heights = [162, 185, 174, 191]
----> 2 print(heights + 1)

TypeError: can only concatenate list (not "int") to list
```
However, this does work if `heights` is a numpy array. 

### Exercise 3: Array arithmetic

In the cell below: 
1. Create a variable called `heights_array`, which contains a numpy array of `heights` (using the `np.array` function we learned above)
2. Try adding, multiplying, subtracting, dividing, exponentiating the array

In [16]:
heights = [162, 185, 174, 191]
heights_array = np.array(heights)

In [19]:
heights_array-25

array([137, 160, 149, 166])

In [20]:
heights_array+17

array([179, 202, 191, 208])

In [21]:
heights_array/3.5

array([46.28571429, 52.85714286, 49.71428571, 54.57142857])

In [22]:
heights_array**4

array([ 688747536, 1171350625,  916636176, 1330863361])

### Exercise 4: Inequalities
You can also evaluate inequalities with whole arrays at once. For example if you wanted to find out which values of your array were equal to 185, you would run the following:
```python
heights_array == 185
```
Copy-paste the line of code above into the cell below and run it. Notice the that output is an array of `bool` variables the same length as your heights array. Each value indicates `True` or `False` based on whether that item in the array meets the criteria.

In [24]:
heights_array==185

array([False,  True, False, False])

Using a similar line of code, find which values of the array above are greater than 180: 

In [25]:
heights_array>180

array([False,  True, False,  True])

Notice - numpy arrays don't have to contain numbers (floats and integers). They can be _booleans_, and other things too!

A boolean is a special type with the value `True` or `False`.

### Exercise 5: Fancy indexing 

As we learned in the previous example, when you run an inequality on a numpy array, you get out an array of bool (True or False) values. You can use this bool array select only the values of a numpy array where the bool array is True.

For example, we now want to print only the heights in the array that are greater than 180. First, we could find out which values of `heights` are greater than 180 using the following inequality:
```python
heights_array > 180
```

If you ran that cell, you would get an array like this: `array([False,  True, False,  True])`. You can then use that array to select only the values from heights_array where the value is True. Like this:


```python
print(heights_array[heights_array>180])
```

Copy-paste the line above and run it in the cell below. Double-check that the result is what you expect.

In [26]:
print(heights_array[heights_array>180])

[185 191]


Now find out which values of `heights_array` are less than 180 using a similar approach:

In [27]:
print(heights_array[heights_array<180])

[162 174]


In Exercise 5, you found that you can figure out which numbers in the array were greater than 180 all at once. It turns out, if you save that array of booleans: 

```python
heights_gt_180 = heights_array > 180
```

You can use `heights_gt_180` like a group of indices on `heights_array` to get just the heights where `heights_gt_180 == True`. 

In the cell below, try:
```python
heights_gt_180 = heights_array > 180
print(heights_array[heights_gt_180])
```
Did it print out the right indices? What if you flip the greater than to a less than? What if you try `==` instead?

In [29]:
heights_gt_180 = heights_array == 180
print(heights_array[heights_gt_180])

[]


## Putting it all together

Using all of these skills together, let's do something that we couldn't do easily with a scientific calculator. Let's find sum of all of the positive, even numbers less than 10,000.

We'll do that in a few steps below: 

First, use `np.arange` to create a list of even integers up to 10,000. Remember that when using np.arange you give it (start,stop,step). So if you use a step of 2 and the first number is even, you will get even numbers only.

In [30]:
even_numbers = np.arange(0,10000,2) 

Now, find the sum of all of these even_numbers using `np.sum`.

In [31]:
np.sum(even_numbers)

24995000

*Extra* One really cool thing about coding is that there are ALWAYS multiple ways to solve a problem! Run the code in the cells below, which both solve the exact same problem that we just solved in Exercise 5 a slightly different way. We haven't learned all of these methods yet, so feel free to look them up on Google if you want to understand how/why they work:

In [32]:
consecutive_integers = np.arange(10000)
even_numbers = consecutive_integers[0::2] 
#This is a fancy style of indexing that uses a second colon. 
#Think of it as [start:stop:step] but in this case no stop is listed, 
#so it goes from index 0 to the end by steps of 2

print(even_numbers)
print(np.sum(even_numbers))

[   0    2    4 ... 9994 9996 9998]
24995000


In [33]:
consecutive_integers = np.arange(10000)
even_numbers = consecutive_integers[consecutive_integers%2==0]
#Remember mod from lesson 2?

print(even_numbers)
print(np.sum(even_numbers))

[   0    2    4 ... 9994 9996 9998]
24995000


***

### Exercise 6

Using the above steps as a template, figure out the sum of the **odd** numbers less than **100,000** TWO different ways:

In [38]:
odd_numbers = np.arange(1,100000,2)
print(odd_numbers)
print(np.sum(odd_numbers))

[    1     3     5 ... 99995 99997 99999]
2500000000


In [36]:
consecutive_integers = np.arange(10000)
odd_numbers = consecutive_integers[1::2] 

print(odd_numbers)
print(np.sum(odd_numbers))

[   1    3    5 ... 9995 9997 9999]
25000000


In [37]:
consecutive_integers = np.arange(10000)
odd_numbers = consecutive_integers[consecutive_integers%2==1]
#Remember mod from lesson 2?

print(odd_numbers)
print(np.sum(odd_numbers))

[   1    3    5 ... 9995 9997 9999]
25000000
